www_programacion/apps/accounts/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import (AppAccountsView, RegistrarUsuario, activate,
                    activation_sent_view, status_task_signup, LoginView,
                    ProfileView, LogoutView, PasswordChangeView,
                    PasswordChangeDoneView, profile_update_field)
from django.urls import reverse, reverse_lazy

app_name = 'accounts'

urlpatterns = [
    path('', AppAccountsView.as_view(), name='application'),
    path('app', AppAccountsView.as_view(), name='application'),
    path('login/', LoginView.as_view(), name='login'),
    path(
        'logout',
        LogoutView.as_view(),  # not override template
        name='logout'),
    path('password_change',
         PasswordChangeView.as_view(
             template_name="registration/password_change.dj.html",
             extra_context={'menu': True}),
         name='password_change'),
    path('password_change/done',
         PasswordChangeDoneView.as_view(
             template_name="registration/password_change_done.dj.html",
             extra_context={'menu': True}),
         name='password_change_done'),
    path('password_reset',
         auth_views.PasswordResetView.as_view(
             template_name="registration/password_reset.dj.html",
             email_template_name="registration/password_reset_email.dj.html",
             html_email_template_name="registration/password_reset_email.dj.html",
             subject_template_name="registration/password_reset_subject.txt",
             success_url=reverse_lazy("accounts:password_reset_done"),
             extra_context={'menu': True}),
         name='password_reset'),
    path('password_reset/done',
         auth_views.PasswordResetDoneView.as_view(
             template_name="registration/password_reset_done.dj.html",
             extra_context={'menu': True}),
         name='password_reset_done'),
    path('password-reset/confirm/uidb64=<uidb64>/token=<token>',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='registration/password_reset_confirm.dj.html',
             success_url=reverse_lazy('accounts:password_reset_complete'),
             extra_context={'menu': True}),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='registration/password_reset_complete.dj.html',
             extra_context={'menu': True}),
         name='password_reset_complete'),
    path("signup/", RegistrarUsuario.as_view(), name='signup'),
    path('activacion-enviada/task=<task_code>',
         activation_sent_view,
         name='activacion-enviada'),
    path('activar/uidb64=<uidb64>/token=<token>/', activate, name='activate'),
    path("ajax/status_task/task=<str:task_id>",
         status_task_signup,
         name="status_task"),
    path("perfil/", ProfileView.as_view(), name='profile'),
    path("perfil/usuario=<str:username>",
         ProfileView.as_view(),
         name='profile_user'),
    path("perfil/update_field/usuario=<str:username>",
         profile_update_field,
         name='profile_update_field'),
]

www_programacion/apps/inscripcion/urls.py
from django.conf.urls import url
from django.urls import path

from apps.inscripcion import views

app_name = 'inscripcion'

urlpatterns = [
    # app view
    path("", views.InscriptionAppView.as_view(), name='application'),
    # logit-auth
    # manage inscripcion by projects
    # activo, en_curso, pasado
    path("proyectos",
         views.InscriptionProjectsView.as_view(),
         name='list_projects_all'),
    path("proyectos/seleccion=<str:choice>",
         views.InscriptionProjectsView.as_view(),
         name='list_projects'),
    path("proyecto/administrar=<slug:slug_generacion>",
         views.InscriptionProjectView.as_view(),
         name='project_admin'),
    # manage inscripcion by projects
    # choices: todas, activas, revision, rechazadas
    path("inscritos",
         views.InscriptionInscribedView.as_view(),
         name='list_inscribed_all'),
    path("inscritos/seleccion=<str:choice>",
         views.InscriptionInscribedView.as_view(),
         name='list_inscribed'),
    # logit-auth
    # manage inscripcion by projects
    path("proyecto/name=<slug:slug_curso>/gen=<slug:slug_generation>",
         views.InscriptionProjectView.as_view(),
         name='person_project'),
    # logit-auth
    path('activas', views.InscripcionesActivasView.as_view(), name='activas'),
    # login-auth
    path('pasadas', views.InscripcionesPasadasView.as_view(), name='pasadas'),
    # normal user
    path('<slug:slug_curso>/<slug:slug_generacion>',
         views.InscripcionView.as_view(),
         name='persona'),
    # normal user
    path('exitosa/<int:id>/<str:valor_aleatorio>',
         views.InscripcionExitosa.as_view(),
         name='exitosa'),
    path("postulante/num=<int:pk>",
         views.InscripcionPostulanteView.as_view(),
         name='postulante'),
    path("ajax/preview/email",
         views.ajax_preview_email,
         name="preview_postulante")
]

www_programacion/apps/proyecto/urls.py
from django.conf.urls import url
from django.urls import path

from apps.proyecto import views
from .feed import LatestProjects
app_name = 'proyecto'

urlpatterns = [
    path('', views.ProjectAppView.as_view(), name='application'),
    path('mis_cursos/', views.MisCursos.as_view(), name='my_courses'),
    # curso
    path('curso/listar', views.CourseListView.as_view(), name='course_list'),
    path('curso/crear', views.CourseCreateView.as_view(),
         name='course_create'),
    path('curso/nombre=<slug:slug_nombre>',
         views.CourseDetailView.as_view(),
         name='course_detail'),
    path('curso/editar/nombre=<slug:slug_nombre>',
         views.CourseEditView.as_view(),
         name='course_edit'),
    path('curso/borrar/nombre=<slug:slug_nombre>',
         views.CourseDeleteConfirmView.as_view(),
         name='course_delete'),
    # project
    path('proyecto/listar',
         views.ProjectListView.as_view(),
         name='project_list'),
    path('proyecto/crear',
         views.ProjectCreateView.as_view(),
         name='project_create'),
    path('proyecto/show=<slug:slug_curso>/gen=<slug:slug_generacion>',
         views.ProjectCourseGenerationView.as_view(),
         name='course_generation'),
    path('proyecto/<slug:slug_curso>/<slug:slug_generacion>',
         views.ProjectDetailView.as_view(),
         name='project_detail'),
    path('proyecto/editar/nombre=<slug:slug_generacion>',
         views.ProjectEditView.as_view(),
         name='project_edit'),
    path('proyecto/borrar/nombre=<slug:slug_generacion>',
         views.ProjectDeleteConfirmView.as_view(),
         name='project_delete'),
    path('feed/', LatestProjects()),
    # email templates
    path('emails/listar', views.EmailsListView.as_view(), name='emails_list'),
    path('emails/crear',
         views.EmailsCreateView.as_view(),
         name='emails_create'),
    path('emails/editar/<int:pk>',
         views.EmailsEditView.as_view(),
         name='emails_edit'),
    path('emails/<int:pk>',
         views.EmailsDetailView.as_view(),
         name='emails_detail'),
    path('emails/borrar/<int:pk>',
         views.EmailsDeleteConfirmView.as_view(),
         name='emails_delete'),
    path('emails/preview/<int:pk>/field=<slug:field>',
         views.EmailsPreviewView.as_view(),
         name='emails_preview'),
    # clasification
    path('clasificacion/listar',
         views.ClasificationListView.as_view(),
         name='clasification_list'),
    path('clasificacion/crear',
         views.ClasificationCreateView.as_view(),
         name='clasification_create'),
    path('clasification/nombre=<slug:slug_tipo>',
         views.ClasificationDetailView.as_view(),
         name='clasification_detail'),
    path('clasificacion/editar/nombre=<slug:slug_tipo>',
         views.ClasificationEditView.as_view(),
         name='clasification_edit'),
    path('clasificacion/borrar/nombre=<slug:slug_tipo>',
         views.ClasificationDeleteConfirmView.as_view(),
         name='clasification_delete'),
    # valor
    path('valor/listar',
         views.CourseValueListView.as_view(),
         name='coursevalue_list'),
    path('valor/crear',
         views.CourseValueCreateView.as_view(),
         name='coursevalue_create'),
    path('valor/id=<int:pk>',
         views.CourseValueDetailView.as_view(),
         name='coursevalue_detail'),
    path('valor/editar/id=<int:pk>',
         views.CourseValueEditView.as_view(),
         name='coursevalue_edit'),
    path('valor/borrar/id=<int:pk>',
         views.CourseValueDeleteConfirmView.as_view(),
         name='coursevalue_delete'),
]

www_programacion/www_programacion/urls.py
from apps.home.views import (page_not_found, bad_request, permission_denied,
                             server_error)
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('404/', page_not_found),
    path('403/', permission_denied),
    path('400/', bad_request),
    path('500/', server_error),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('cuentas/',
         include('apps.accounts.urls', namespace='accounts'),
         name='accounts'),
    path('perfil/',
         include('apps.perfil_usuario.urls', namespace='perfil'),
         name='perfil'),
    path('', include('apps.home.urls', namespace='home'), name='home'),
    path('pagina/',
         include('apps.pagina.urls', namespace='pagina'),
         name='pagina'),
    path('inscripcion/',
         include('apps.inscripcion.urls', namespace='inscripcion'),
         name='inscripcion'),
    path('contacto/',
         include('apps.contacto.urls', namespace='contacto'),
         name='contacto'),
    path('proyecto/',
         include('apps.proyecto.urls', namespace='proyecto'),
         name='proyecto'),
    path('organizacion/',
         include('apps.organizacion.urls', namespace='organizacion'),
         name='organizacion'),
    path('captcha/', include('captcha.urls'), name='captcha'),
    path("admin_group/",
         include('apps.admin_group.urls', namespace='admin_group'),
         name='admin_group'),
    path('groups_manager/',
         include('groups_manager.urls', namespace='groups_manager'),
         name='groups_manager'),
    path("contenido/",
         include("apps.contenido.urls", namespace='contenido'),
         name='contenido')
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

www_programacion/apps/inscripcion/models.py
from django.db import models
from django.utils.text import slugify
import ujson as json
from phonenumber_field.modelfields import PhoneNumberField
from apps.proyecto.models import Proyecto
from markdownx.models import MarkdownxField

from django.contrib.auth.models import User


def get_upload_inscripcion_file_name(instance, filename):
    sg = instance.proyecto.slug_generacion
    return "inscripcion/patrocinio/%s/%s" % (sg, filename)


class ChequeoCodigo(models.Model):
    valor_aleatorio = models.CharField(max_length=10)

    class Meta:
        app_label = "inscripcion"
        verbose_name = "Código de Chequeo"
        verbose_name_plural = "Códigos de Chequeo"
        ordering = ('valor_aleatorio', )

    def __repr__(self):
        return json.dumps(self.__dict__)

    def __str__(self):
        return self.valor_aleatorio


class Inscripcion(models.Model):
    ON_REVIEW = "on_review"
    ACCEPTED = "accepted"
    REJECTED = "rejected"
    DEFAULT_MSG = "Tu postulación fue..."
    ACEPTA_DEFAULT = "¡Has sido aceptad@!"
    RECHAZA_DEFAULT = "¡Has sido rechazad@!"
    STATUS_CHOICES = [(ON_REVIEW, "Revisión"), (ACCEPTED, "Aceptada"),
                      (REJECTED, "Rechazada")]
    usuario = models.ForeignKey(User,
                                related_name="inscripciones",
                                on_delete=models.SET_NULL,
                                null=True)
    representa_organizacion = models.BooleanField(default=False)
    organizacion = models.CharField(max_length=100, blank=True)
    web_organizacion = models.URLField(max_length=200,
                                       default="http://sinweb.com")
    carta_patrocinio = models.FileField(
        upload_to=get_upload_inscripcion_file_name, blank=True)
    motivacion = models.TextField()
    proyecto = models.ForeignKey(Proyecto,
                                 related_name="inscripciones",
                                 on_delete=models.CASCADE,
                                 blank=True,
                                 null=True)
    valor_aleatorio = models.CharField(max_length=10)
    fecha_inscripcion = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=20,
                              choices=STATUS_CHOICES,
                              default=ON_REVIEW)

    def get_absolute_url(self):
        return reverse('inscripcion:persona',
                       kwargs={
                           'slug_curso': self.proyecto.curso.slug_nombre,
                           'slug_generacion': self.proyecto.slug_generacion
                       })

    @property
    def persona(self):
        if self.usuario:
            return "%s %s %s- %s - %s" % (
                self.usuario.first_name, self.usuario.profile.father_last_name,
                self.usuario.profile.mother_last_name,
                self.usuario.profile.email, self.usuario.profile.phonenumber)
        else:
            return "Sin usuario"

    @property
    def nombre_completo(self):
        if self.usuario:
            return "%s %s %s" % (self.usuario.profile.first_name,
                                 self.usuario.profile.father_last_name,
                                 self.usuario.profile.mother_last_name)
        else:
            return "Sin usuario"

    class Meta:
        app_label = "inscripcion"
        verbose_name = "Inscripción"
        verbose_name_plural = "Inscripciones"
        ordering = (
            '-fecha_inscripcion',
            "usuario",
            'proyecto',
        )
        permissions = [("can_apply", "Puede inscribirse")]

    def __repr__(self):
        return f"Inscripcion({self.proyecto.curso}, {self.proyecto}, {self.usuario})"

    def __str__(self):
        return self.persona

    @property
    def css_status(self):
        return f"color-{self.status}"

    @property
    def username(self):
        return self.usuario.username


from django.contrib.postgres.fields import JSONField


class RevisionInscripcion(models.Model):
    def DEFAULT_JSON():
        return dict(usuario=[], admins=[])

    DEFAULT_MSG = "Tu postulación fue..."
    ACEPTA_DEFAULT = "¡Has sido aceptad@!"
    RECHAZA_DEFAULT = "¡Has sido rechazad@!"
    promesa = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_time = models.DateTimeField(auto_now=True)
    inscripcion = models.ForeignKey(Inscripcion, on_delete=models.CASCADE)
    mensaje = models.TextField(default=DEFAULT_MSG, blank=True)
    enviados = JSONField(default=DEFAULT_JSON)

    class Meta:
        app_label = "inscripcion"
        verbose_name = "Revisión de Inscripción"
        verbose_name_plural = "Revisiones de Inscripciones"
        ordering = (
            '-date_time',
            "inscripcion",
            'user',
        )
        permissions = [("can_review", "Puede revisar")]

    def __str__(self):
        return f"{self.user.profile}->{self.inscripcion}:{self.date_time}"

    def __repr__(self):
        return f"{self.user.profile}->{self.inscripcion}:{self.date_time}"

www_programacion/apps/inscripcion/templates/inscripcion/admin_proyecto.dj.html
{% extends 'inscripcion/base.dj.html' %}

{% block breadcrumbs %}
{{block.super}}
<li>
    <a href="{% url 'inscripcion:application' %}">Proyecto {{object.curso}}|{{object}}</a>
</li>
{% endblock breadcrumbs %}


{% block content_inscripcion %}
<!-- Project Info Here -->
<div class="tile is-child box">
    {% include 'proyecto/proyecto/basic_info.dj.html' %}
</div>
<!-- Users table here -->
<div class="tile is-child box">
    {% include 'inscripcion/users_table.dj.html' with object_list=object.inscripciones.all %}
</div>
<div class="tile is-child box">
    <div class="tile"><h3 class="title is-3">Sumario Inscripciones</h3></div>
    <!-- SUMARIO: ON_REVIEW, ACCEPTED, REJECTED -->
    {% include 'inscripcion/sumario.dj.html' %}
</div>
<div class="tile is-child box">
    <h1 class="button is-large is-rounded is-fullwidth is-info">Comunicar
        Resultados</h1>
    <!-- send post and tasks to send emails from json selected with edition -->
</div>
{% endblock %}

www_programacion/apps/inscripcion/templates/inscripcion/app.dj.html
{% extends 'inscripcion/base.dj.html' %}

{% block content_inscripcion %}
    <div class="tile is-child">
        <h3 class="title is-3">
            Administrar Inscripciones
        </h3>
    </div>
    <div class="tile is-parent">
    <div class="tile is-child is-6">
        <a href="{% url 'inscripcion:list_projects_all' %}">Por proyecto</a>
    </div>
    <div class="tile is-child is-6">
        <a href="{% url 'inscripcion:list_inscribed_all' %}">Por Inscripción</a>
    </div>
    </div>
{% endblock %}

www_programacion/apps/inscripcion/templates/inscripcion/email_nueva_inscripcion.dj.html
{% load inlinecss %}
{% inlinecss "inscripcion/css/email.css" %}
<html>
    <body>
        <article>
            <h1>Inscripción a Curso de Programación para Organizaciones
                Comunitarias</h1>
            <ul>
                <li>{{data_persona.username}}</li>
                <li>{{data_persona.nombre_completo}}</li>
                <li>{{data_persona.email}}</li>
                <li>{{data_persona.phonenumber}}</li>
            </ul>
        </article>
    </body>
</html>
{% endinlinecss %}

www_programacion/apps/inscripcion/templates/inscripcion/form_postulante.dj.html
{% load widget_tweaks %}
{% load static %}

<h4 class="title is-4">Formulario de aceptación</h4>
<form action="{{request.get_full_path}}" method="post"
      enctype="multipart/form-data"
      role="form" class="django form">
    {% csrf_token %}
    <div class="field is-horizontal">
        <div class="field-label">
        <label class="label">
            {{form.status.label}}
        </label>
        </div>
        <div class="field-body">
        <div class="control is-fullwidth">
            <div class="select">
                {% render_field form.status class+="input select" type="select" id+="select_status" %}
            </div>
        </div>
        </div>
    </div>
    <div  class="field is-horizontal"  id="field_mensaje">
        <div class="field-label is-normal">
            <label class="label"
                   for="{{form.mensaje.id_for_label}}">
                {{form.mensaje.label}}</label>
        </div>
        <div class="field-body">
            <div class="columns">

                <div class="column is-8">
            <div class="control">
                {% render_field form.mensaje class+="textarea" type="textarea" id+="message" %}</div>
            <span class="help is-invalid">{{ form.mensaje.errors }}</span>
                </div>
                <div class="column">
                    <p>Ingresa un mensaje que corresponderá al parámetro "mensaje_particular"</p>

                    <a class="button is-warning is-fullwidth"  target=”_blank”
                       href="{% url 'proyecto:emails_edit' inscripcion.proyecto.email_templates.id %}"
                       id="edit_mail_templates">
                        <i class="fas fa-eye"></i>Editar Mensajes</a>
                    <button class="button is-info is-fullwidth" type="button"
                            onclick="show_message_preview()"
                            id="link_preview">
                        <i class="fas fa-eye"></i>Preview</button>

                </div>
            </div>
        </div>
    </div>

    <div class="field is-horizontal">
        <div class="field-label">
            <label class="label">
                <input type="checkbox" id="checkbox_promesa" onclick="handleChange(this)">
                {{form.promesa.label}}
            </label>
        </div>
        <div class="field-body">
            <div>He revisado a conciencia la postulación de {{inscripcion.usuario}}</div>
        </div>
    </div>

    <div class="is-hidden">
    {% render_field form.inscripcion class+="input" type="input" id+="id_inscripcion" value=form.inscripcion.initial %}
    {% render_field form.user class+="input" type="input" id+="select_status" value=form.user.initial %}
    </div>


    <div class="buttons are-medium columns">
        <div class="column">
            <button type="submit" class="button is-primary is-fullwidth" id="send_button" disabled>Enviar Resultado</button></div>
        <div class="column ">
            <a class="button is-warning is-fullwidth" href={% if group %}
               "{% url 'inscripcion:project_admin' inscripcion.proyecto.slug_generacion %}"
               {% else %}
               "{% url 'inscripcion:list_inscribed_all' %}"{% endif %}>
                Cancelar</a></div>
    </div>

</form>
{% include 'inscripcion/modal_email.dj.html' %}
<div class="is-hidden">
    <div id="texto_review">{{inscripcion.DEFAULT_MSG}}</div>
    <div id="texto_acepta">{{inscripcion.ACEPTA_DEFAULT}}</div>
    <div id="texto_rechazo">{{inscripcion.RECHAZA_DEFAULT}}</div>
</div>
<script>
 /*
    Al cambiar el select de status... :=> on change
    Completar el campo de texto por
  */
 let url_acepta="{% url 'proyecto:emails_preview' inscripcion.id 'acepta' %}"
 let url_rechaza="{% url 'proyecto:emails_preview' inscripcion.id 'rechaza' %}"
 let review = document.getElementById("texto_review").innerHTML;
 let acepta = document.getElementById("texto_acepta").innerHTML;
 let rechazo = document.getElementById("texto_rechazo").innerHTML;
 let status_elem = document.getElementById("select_status");
 let message_elem = document.getElementById("message");
 let link = document.getElementById("link_preview");
 status_elem.addEventListener("change", event=>{
     let target=event.target;
     let sel=target.value;
     if (sel==="accepted"){
         message_elem.innerHTML = acepta;
         link.setAttribute("href", url_acepta);
     }
     else if(sel==="rejected"){
         message_elem.innerHTML = rechazo;
         link.setAttribute("href", url_rechaza);
     }
     else{
         message_elem.innerHTML = review;
         link.setAttribute("href", "");
     }
 });

 /*
    $.ajax({
    url: "/ajax/",
    type: "POST",
    data: name,
    cache:false,
    dataType: "json",
    success: function(resp){
    alert ("resp: "+resp.name);
    }
    });*/

 function active_modal_message(modal_id, data){
     let modal=document.getElementById(modal_id);
     let content=document.getElementById("content_message_preview");
     content.innerHTML=data["email_html"];
     let title=document.getElementById("modal_title");
     title.innerHTML = data.title;
     modal.classList.add("is-active");
     let close = document.getElementById("close_modal");
     close.addEventListener("click", event=>{
         modal.classList.remove("is-active");
     });
     let close_up = document.getElementById("close_modal_up");
     close_up.addEventListener("click", event=>{
         modal.classList.remove("is-active");
     });

 }

 function ajax_message_preview(url, data, modal_id, callback){
     /*
        username: nombre d 
        usuario
        field_name: nombre del campo a modificar
        value: valor modificado
        field: campo

      */
     var csrftoken = getCookie('csrftoken');
     let xhr = new XMLHttpRequest();
     xhr.open('POST', url, true);
     xhr.onload = function result_update_field(event){
         let data_txt = xhr.responseText;
         let data_json = JSON.parse(data_txt);
         if (xhr.readyState==4){
             if (xhr.status==200){
                 callback(modal_id, data_json);
             }
             else{
                 console.log("Error al recibir");
             }
         }

     };

     xhr.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
     xhr.setRequestHeader("Content-Type", "application/json;charset=UTF-8");
     xhr.setRequestHeader("X-CSRFToken", csrftoken);
     let json_string =JSON.stringify(data);
     console.log("Send msg", json_string);
     xhr.send(json_string);
 }
 // call ajax
 let inscripcion_id = "{{inscripcion.id}}";

 function show_message_preview(){
     let url="{% url 'inscripcion:preview_postulante' %}";
     let txt_html = document.getElementById("message").value;
     let txt_tipo = document.getElementById("select_status").value;
     let data = {mensaje_particular:txt_html, inscripcion:inscripcion_id, tipo:txt_tipo};
     console.log("Sending data...", data);
     ajax_message_preview(url, data, "modal_email", active_modal_message);
 }
 /* listen checkbox event on True=>button send disable false*/
 function handleChange(checkbox){
     let button=document.getElementById("send_button");
     if(checkbox.checked == true){
         button.disabled=false;
     }
     else if(checkbox.checked == false){
         button.disabled=true;
     }

 }
</script>

www_programacion/apps/inscripcion/templates/inscripcion/main_menu.dj.html
<h4 class="title is-4"><a href="{% url 'proyecto:application' %}">
    Administrar Inscripciones</a></h4>

{% include 'components/accordion_menu.dj.html' %}

www_programacion/apps/inscripcion/templates/inscripcion/por_inscripcion.dj.html
{% extends 'inscripcion/base.dj.html' %}

{% block breadcrumbs %}
{{block.super}}
<li>
    <a href="{% url 'inscripcion:application' %}">Por inscripción</a>
</li>
{% endblock breadcrumbs %}

{% block content_inscripcion %}
<div class="tile is-child">
    <h3 class="title is-3">
        Últimas inscripciones
    </h3>
</div>

<div class="tile is-child">
    {% include 'inscripcion/users_table.dj.html' %}
</div>

<div class="tile is-child">
    {% include 'components/paginate.dj.html' %}
</div>
<div class="tile is-child">
    <!-- SUMARIO: ON_REVIEW, ACCEPTED, REJECTED -->
    {% if perms.groups_manager.can_change_inscripcion %}
    {% include 'inscripcion/sumario.dj.html' %}
    {% endif %}
</div>


{% endblock %}

www_programacion/apps/inscripcion/templates/inscripcion/por_proyecto.dj.html
{% extends 'inscripcion/base.dj.html' %}

{% block breadcrumbs %}
{{block.super}}
<li>
    <a href="{% url 'inscripcion:application' %}">Por proyecto</a>
</li>
{% endblock breadcrumbs %}


{% block content_inscripcion %}
<div class="tile is-child">
    <h3 class="title is-3">
        Proyectos relevantes | {{choice}}
    </h3>
</div>
<div class="tile is-child">
    <table class="table is-hoverable is-fullwidth is-striped" id="group_list">
        <thead>
            <tr>
                <th>Afiche</th>
                <th>Tótem</th>
                <th>Curso</th>
                <th>Generación</th>
                <th>Fecha Inicio</th>
                <th>Fecha Final</th>
                <th>Acción</th>
            </tr>
        </thead>
        <tbody>
            {% for project in object_list %}
            <tr>
                <!-- afiche (thumb) field -->
                <td><img src="{{project.afiche.url}}" width="60px" height="60px"
                         alt="Afiche curso"></td>
                <!-- afiche (thumb) field -->
                <td><img src="{{project.icono_totem.url}}" width="60px" height="auto"
                         alt="Icono toem"></td>
                <!-- curso field -->
                <td><a href="{{project.get_absolute_url}}">{{project.curso}}</a></td>
                <!-- generacion field -->
                <td>{{project.generacion}}</td>
                <!-- fecha inicio field -->
                <td>{{project.fecha_inicio}}</td>
                <!-- fecha final field -->
                <td>{{project.fecha_final}}</td>
                <!-- valores -->
                <td>
                    {% if perms.groups_manager.can_change_inscripcion %}
                    <a class="button is-info" href="{% url 'inscripcion:project_admin' project.slug %}">
                        Admnistrar Inscripciones</a>
                    {% else %}
                    Ver mi inscripción
                    {% endif %}


                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% include 'components/paginate.dj.html' %}
</div>
{% endblock %}

www_programacion/apps/inscripcion/templates/inscripcion/postulante.dj.html
{% extends 'inscripcion/base.dj.html' %}

{% block breadcrumbs %}
{{block.super}}
<li>
    <a href="{% url 'inscripcion:application' %}">Postulante</a>
</li>
{% endblock breadcrumbs %}


{% block content_inscripcion %}
<div class="tile is-child">
    {% include 'inscripcion/detail_postulante.dj.html'  %}
</div>
<div class="tile is-child">
    {% include 'inscripcion/detail_inscripcion.dj.html'  %}
</div>
<div class="tile is-child">
    {% include 'inscripcion/form_postulante.dj.html' %}
</div>
{% endblock %}