www_programacion/apps/contacto/urls.py
from django.conf.urls import url
from django.urls import path
# from django.contrib import admin
from apps.contacto.views import ContactoView, contacto_sent_view, status_task_contacto

app_name = 'contacto'

urlpatterns = [
    path('', ContactoView.as_view(), name='formulario'),
    path('exitoso/', contacto_sent_view, name='exitoso'),
    path("ajax/contacto/task=<str:task_id>",
         status_task_contacto,
         name="email-enviado"),
]

www_programacion/apps/inscripcion/urls.py
from django.conf.urls import url
from django.urls import path

from apps.inscripcion import views

app_name = 'inscripcion'

urlpatterns = [
    # app view
    path("", views.InscriptionAppView.as_view(), name='application'),
    # logit-auth
    # manage inscripcion by projects
    # activo, en_curso, pasado
    path("proyectos",
         views.InscriptionProjectsView.as_view(),
         name='list_projects_all'),
    path("proyectos/seleccion=<str:choice>",
         views.InscriptionProjectsView.as_view(),
         name='list_projects'),
    path("proyecto/administrar=<slug:slug_generacion>",
         views.InscriptionProjectView.as_view(),
         name='project_admin'),
    # manage inscripcion by projects
    # choices: todas, activas, revision, rechazadas
    path("inscritos",
         views.InscriptionInscribedView.as_view(),
         name='list_inscribed_all'),
    path("inscritos/seleccion=<str:choice>",
         views.InscriptionInscribedView.as_view(),
         name='list_inscribed'),
    # logit-auth
    # manage inscripcion by projects
    path("proyecto/name=<slug:slug_curso>/gen=<slug:slug_generation>",
         views.InscriptionProjectView.as_view(),
         name='person_project'),
    # logit-auth
    path('activas', views.InscripcionesActivasView.as_view(), name='activas'),
    # login-auth
    path('pasadas', views.InscripcionesPasadasView.as_view(), name='pasadas'),
    # normal user
    path('<slug:slug_curso>/<slug:slug_generacion>',
         views.InscripcionView.as_view(),
         name='persona'),
    # normal user
    path('exitosa/<int:id>/<str:valor_aleatorio>',
         views.InscripcionExitosa.as_view(),
         name='exitosa'),
    path("postulante/num=<int:pk>",
         views.InscripcionPostulanteView.as_view(),
         name='postulante'),
    path("ajax/preview/email",
         views.ajax_preview_email,
         name="preview_postulante")
]

www_programacion/apps/proyecto/urls.py
from django.conf.urls import url
from django.urls import path

from apps.proyecto import views
from .feed import LatestProjects
app_name = 'proyecto'

urlpatterns = [
    path('', views.ProjectAppView.as_view(), name='application'),
    path('mis_cursos/', views.MisCursos.as_view(), name='my_courses'),
    # curso
    path('curso/listar', views.CourseListView.as_view(), name='course_list'),
    path('curso/crear', views.CourseCreateView.as_view(),
         name='course_create'),
    path('curso/nombre=<slug:slug_nombre>',
         views.CourseDetailView.as_view(),
         name='course_detail'),
    path('curso/editar/nombre=<slug:slug_nombre>',
         views.CourseEditView.as_view(),
         name='course_edit'),
    path('curso/borrar/nombre=<slug:slug_nombre>',
         views.CourseDeleteConfirmView.as_view(),
         name='course_delete'),
    # project
    path('proyecto/listar',
         views.ProjectListView.as_view(),
         name='project_list'),
    path('proyecto/crear',
         views.ProjectCreateView.as_view(),
         name='project_create'),
    path('proyecto/show=<slug:slug_curso>/gen=<slug:slug_generacion>',
         views.ProjectCourseGenerationView.as_view(),
         name='course_generation'),
    path('proyecto/<slug:slug_curso>/<slug:slug_generacion>',
         views.ProjectDetailView.as_view(),
         name='project_detail'),
    path('proyecto/editar/nombre=<slug:slug_generacion>',
         views.ProjectEditView.as_view(),
         name='project_edit'),
    path('proyecto/borrar/nombre=<slug:slug_generacion>',
         views.ProjectDeleteConfirmView.as_view(),
         name='project_delete'),
    path('feed/', LatestProjects()),
    # email templates
    path('emails/listar', views.EmailsListView.as_view(), name='emails_list'),
    path('emails/crear',
         views.EmailsCreateView.as_view(),
         name='emails_create'),
    path('emails/editar/<int:pk>',
         views.EmailsEditView.as_view(),
         name='emails_edit'),
    path('emails/<int:pk>',
         views.EmailsDetailView.as_view(),
         name='emails_detail'),
    path('emails/borrar/<int:pk>',
         views.EmailsDeleteConfirmView.as_view(),
         name='emails_delete'),
    path('emails/preview/<int:pk>/field=<slug:field>',
         views.EmailsPreviewView.as_view(),
         name='emails_preview'),
    # clasification
    path('clasificacion/listar',
         views.ClasificationListView.as_view(),
         name='clasification_list'),
    path('clasificacion/crear',
         views.ClasificationCreateView.as_view(),
         name='clasification_create'),
    path('clasification/nombre=<slug:slug_tipo>',
         views.ClasificationDetailView.as_view(),
         name='clasification_detail'),
    path('clasificacion/editar/nombre=<slug:slug_tipo>',
         views.ClasificationEditView.as_view(),
         name='clasification_edit'),
    path('clasificacion/borrar/nombre=<slug:slug_tipo>',
         views.ClasificationDeleteConfirmView.as_view(),
         name='clasification_delete'),
    # valor
    path('valor/listar',
         views.CourseValueListView.as_view(),
         name='coursevalue_list'),
    path('valor/crear',
         views.CourseValueCreateView.as_view(),
         name='coursevalue_create'),
    path('valor/id=<int:pk>',
         views.CourseValueDetailView.as_view(),
         name='coursevalue_detail'),
    path('valor/editar/id=<int:pk>',
         views.CourseValueEditView.as_view(),
         name='coursevalue_edit'),
    path('valor/borrar/id=<int:pk>',
         views.CourseValueDeleteConfirmView.as_view(),
         name='coursevalue_delete'),
]

www_programacion/www_programacion/urls.py
from apps.home.views import (page_not_found, bad_request, permission_denied,
                             server_error)
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('404/', page_not_found),
    path('403/', permission_denied),
    path('400/', bad_request),
    path('500/', server_error),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('cuentas/',
         include('apps.accounts.urls', namespace='accounts'),
         name='accounts'),
    path('perfil/',
         include('apps.perfil_usuario.urls', namespace='perfil'),
         name='perfil'),
    path('', include('apps.home.urls', namespace='home'), name='home'),
    path('pagina/',
         include('apps.pagina.urls', namespace='pagina'),
         name='pagina'),
    path('inscripcion/',
         include('apps.inscripcion.urls', namespace='inscripcion'),
         name='inscripcion'),
    path('contacto/',
         include('apps.contacto.urls', namespace='contacto'),
         name='contacto'),
    path('proyecto/',
         include('apps.proyecto.urls', namespace='proyecto'),
         name='proyecto'),
    path('organizacion/',
         include('apps.organizacion.urls', namespace='organizacion'),
         name='organizacion'),
    path('captcha/', include('captcha.urls'), name='captcha'),
    path("admin_group/",
         include('apps.admin_group.urls', namespace='admin_group'),
         name='admin_group'),
    path('groups_manager/',
         include('groups_manager.urls', namespace='groups_manager'),
         name='groups_manager'),
    path("contenido/",
         include("apps.contenido.urls", namespace='contenido'),
         name='contenido')
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

www_programacion/apps/proyecto/forms.py
from django import forms
from django_json_widget.widgets import JSONEditorWidget
from .models import EmailTemplates, Curso, Proyecto


class CursoForm(forms.ModelForm):
    class Meta:
        model = Curso
        fields = [
            "nombre", "imagen", "resumen", "descripcion", "clasificacion",
            "usuario"
        ]
        widgets = {'usuario': forms.HiddenInput}


class ProyectoForm(forms.ModelForm):
    fecha_inscripcion_inicio = forms.DateField(
        widget=forms.HiddenInput(attrs={"id": "fecha_inscripcion_inicio"}),
        input_formats=['%d/%m/%Y'])
    fecha_inscripcion_final = forms.DateField(
        widget=forms.HiddenInput(attrs={"id": "fecha_inscripcion_final"}),
        input_formats=['%d/%m/%Y'])
    fecha_inicio = forms.DateField(
        widget=forms.HiddenInput(attrs={"id": "fecha_inicio"}),
        input_formats=['%d/%m/%Y'])
    fecha_final = forms.DateField(
        widget=forms.HiddenInput(attrs={"id": "fecha_final"}),
        input_formats=['%d/%m/%Y'])

    class Meta:
        model = Proyecto
        fields = [
            "curso", "valor", "generacion", "imagen_totem", "icono_totem",
            "afiche", "imagen_fondo", "resumen", "descripcion", "fecha_inicio",
            "fecha_final", "fecha_inscripcion_inicio",
            "fecha_inscripcion_final", "usuario"
        ]
        widgets = {'usuario': forms.HiddenInput}


class EmailTemplatesForm(forms.ModelForm):
    class Meta:
        model = EmailTemplates

        fields = ["proyecto", "parametros"] + list(
            map(lambda x: f"inscripcion_{x}", [
                "exitosa_usuario", "exitosa_admin", "rechazo", "acepta",
                "result_admins"
            ]))

        widgets = {'parametros': JSONEditorWidget(width="600px")}

www_programacion/apps/proyecto/templates/proyecto/proyecto/basic_info.dj.html
<div class="media">
    <figure class="media-left">
        <p class="afiche">
            <img src="{{object.afiche.url}}" alt="{{object.curso}}"
    width="200px" height="auto">
        </p>
    </figure>
    <div class="media-content">
        </div>
        <div class="content">
            <h4 class="title is-4"> {{object.curso.nombre}}</h4>
            <div class="generation-data media">
                <div class="media-content">
                    <img src="{{object.icono_totem.url}}" class="icono">
                    <span class="tag is-info">{{object}}</span>
                </div>
            </div>
            <div class="content mt-5">
                {{object.curso.descripcion|safe|truncatewords:20}}
            </div>
            <div class="">
                {{project}} {{object}}
                <a href="{% url "proyecto:course_generation" object.curso.slug object.slug %}"
                   title="{{object.curso.nombre}}: {{object.generacion}}">
                    Ver el curso</a></div>
        </div>
    </div>

www_programacion/apps/proyecto/templates/proyecto/proyecto/confirm_delete.dj.html
{% extends 'proyecto/delete_base.dj.html' %}
{% load widget_tweaks %}

{% block form_delete%}
<h2 class="title is-2">
    <i class="fa fa-groups-manager-group"></i> Borrar 'Proyecto de Curso'
</h2>
<div class="bs-callout bs-callout-danger">
    <h3 class="title is-3">{{ object }}</h3>
    <p>¿Estás segur@ que deseas borrar este proyecto de curso?</p>
    <p>Todas las relaciones de esta instancia serás borradas también..</p>
    <form action="{{request.get_full_path}}" method="post">
        {% csrf_token %}
        <div class="buttons are-medium columns">
            <div class="column">
                <input type="submit" class="button is-danger is-fullwidth" value="Delete" />
            </div>
            <div class="column">
                <a href="{{object.get_absolute_url}}" class="button
                         is-warning  is-fullwidth">Volver a detalle</a></div>
        </div>
    </form>
</div>
{% endblock form_delete %}

www_programacion/apps/proyecto/templates/proyecto/proyecto/create.dj.html
{% extends 'proyecto/base.dj.html' %}
{% load widget_tweaks %}

{% block content_proyecto%}
<div class="tile is-child">
    <h3 class="title is-3">Crear Proyecto</h3>
</div>
{% if perms.groups_manager.can_add_proyecto %}
<div class="tile is-child">
    <ul>
    {% for error, value in form.errors.items %}
        <li>Falla en campo <i>{{error}}:{{value}}</i></li>
    {% endfor %}
    </ul>

<form action="{{request.get_full_path}}"
      enctype="multipart/form-data"
      method="post"
      id="proyecto_form"
      class="django form">
    {% csrf_token %}

    {% include 'proyecto/proyecto/fields.dj.html' %}

    <div class="buttons are-medium columns">
        <div class="column">
            <button type="submit" class="button
                          is-primary is-fullwidth">Crear</button></div>
        <div class="column ">
            <a class="button is-warning is-fullwidth" href={% if group %}
               "{% url 'proyecto:project_detail' member.id %}"
               {% else %}
               "{% url 'proyecto:project_list' %}"{% endif %}>
                Cancelar</a></div>
    </div>

</form>
</div>
{% else %}
<h3 class="title is-3">Puedes proponer realizar una instancia de proyecto aquí:
    <a href="{% url 'contacto:formulario' %}">Contacto</a></h3>
{% endif %}
{% endblock content_proyecto %}

www_programacion/apps/proyecto/templates/proyecto/proyecto/edit.dj.html
{% extends 'proyecto/base.dj.html' %}
{% load widget_tweaks %}

{% block content_proyecto%}
<div class="tile is-child">
    <h3 class="title is-3">Crear Proyecto</h3>
</div>
{% if perms.groups_manager.can_change_proyecto %}
<div class="tile is-child">

<ul>
    {% for error, value in form.errors.items %}
    <li>Falla en campo <i>{{error}}:{{value}}</i></li>
    {% endfor %}
</ul>


<form action="{{request.get_full_path}}"
      enctype="multipart/form-data"
      method="post"
      id="member_form"
      class="django form">
    {% csrf_token %}

    {% include 'proyecto/proyecto/fields.dj.html' %}

    <div class="buttons are-medium columns">
        <div class="column">
            <button type="submit" class="button
                          is-primary is-fullwidth">Editar</button></div>
        <div class="column ">
            <a class="button is-warning is-fullwidth" href={% if group %}
               "{% url 'proyecto:project_detail' project.slug_generacion %}"
               {% else %}
               "{% url 'proyecto:project_list' %}"{% endif %}>
                Cancelar</a></div>
    </div>

</form>
</div>
{% endif %}
{% endblock content_proyecto %}

www_programacion/apps/proyecto/templates/proyecto/proyecto/list.dj.html
{% extends 'proyecto/base.dj.html' %}

{% block content_proyecto%}
<div class="tile is-child">
<h2 class="title is-2">
    <i class="fa fa-groups-manager-group"></i> Lista de Proyectos 
</h2>
</div>
<div class="tile">
<table class="table is-hoverable is-fullwidth is-striped" id="group_list">
    <thead>
        <tr>
            <th>Afiche</th>
            <th>Tótem</th>
            <th>Curso</th>
            <th>Generación</th>
            <th>Fecha Inicio</th>
            <th>Fecha Final</th>
            <th>Valores</th>
            <th class="has-text-right">Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% for project in object_list %}
        <tr>
            <!-- afiche (thumb) field -->
            <td><img src="{{project.afiche.url}}" width="60px" height="60px"
    alt="Afiche curso"></td>
            <!-- afiche (thumb) field -->
            <td><img src="{{project.icono_totem.url}}" width="60px" height="auto"
    alt="Icono toem"></td>
            <!-- curso field -->
            <td><a href="{% if project.curso %}{{project.get_absolute_url}}
                         {%endif %}">{{project.curso}}</a></td>
            <!-- generacion field -->
            <td>{{project.generacion}}</td>
            <!-- fecha inicio field -->
            <td>{{project.fecha_inicio}}</td>
            <!-- fecha final field -->
            <td>{{project.fecha_final}}</td>
            <!-- valores -->
            <td>
                <ul>
                    {% for valor in project.valor.all %}
                    <li>{{valor}}:${{valor.precio}}</li>
                    {%endfor%}
                </ul>
            </td>
         <!-- action field -->
        <td class="has-text-right">
            <!--PERMISSIONS_HERE-->
            {% if perms.groups_manager.can_change_project %}
            <a href="{% url 'proyecto:project_edit' project.slug_generacion %}"
    class="button is-warning is-block">
                <i class="fa fa-edit"></i>
            </a>
            {% endif %}
            {% if perms.groups_manager.can_delete_project %}
            <a  href="{% url 'proyecto:project_delete' project.slug_generacion %}"
                class="button is-danger is-block">
                <i class="fa fa-times"></i>
            </a>
            {% endif %}
        </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
{% endblock %}

www_programacion/apps/proyecto/templates/proyecto/proyecto/menu_show.dj.html
<div class="sticky">
<h5 class="title is-5">
    {{object.curso}}</h5>
<aside class="menu">
    {% for app, group in show_menu.items %}
    <div class="menu {% if app == app_active %}is-active{% endif%} is-success">
        <p class="menu-label">
            {{app}}
        </p>
        <ul class="menu-list">
            {% for elem in group %}
            <li>{{elem.html|safe}}</li>
            {% endfor %}
        </ul>
    </div>
    {% endfor %}
</aside>
</div>

www_programacion/apps/proyecto/templates/proyecto/proyecto/show.dj.html
{% extends 'proyecto/base.dj.html' %}
{% load static %}

{% block title %}
{{block.super}}|{{object.curso.nombre}}
{% endblock %}

{% block breadcrumbs %}
{{block.super}}
<li>
    <a href="{{object.curso.get_absolute_url}}">{{object.curso}}</a>
</li>
<li class="is-active">
    <a href="{{object.get_absolute_url}}" aria-current="page">{{object}}</a>
</li>
{% endblock breadcrumbs %}


{% block sidebar_left %}
    <div class="tile is-child box sticky">
        {% include "./menu_show.dj.html" %}
    </div>
{% endblock sidebar_left %}

{% block content_article %}
<div id="show_project" class="tile is-ancestor">
    <div class="tile is-parent box is-vertical ">
        <!-- curso imagen -->
        <div class="tile is-child" id="sobre_curso">
        <figure class="content has-text-centered">
            <img src="{{object.curso.imagen.url}}" width="60%">
        </figure>
        <!-- curso nombre -->
        <h3 class="title is-3 has-text-centered">{{object.curso.nombre}}</h3>
        <!-- curso descripcion -->
        <div class="content">
            {{object.curso.descripcion|safe}}
        </div>
        </div>
        <!-- fechas tiling: dos elementos: inscripcion y de curso -->
        <div class="tile is-parent" id="fechas_importantes">
            <div class="tile is-child is-6 box">
                <h3 class="title is-3">Inscripción</h3>
                <input id="inscripcion_dates"
                       type="date"
                       data-display-mode="inline"
                       data-is-range="true"
                       data-close-on-select="false">
            </div>
            <div class="tile is-child is-6 box">
                <h3 class="title is-3">Curso</h3>
                <input id="clases_dates"
                       type="date"
                       data-display-mode="inline"
                       data-is-range="true"
                       data-close-on-select="false">
            </div>            
        </div>
        <div class="tile is-parent is-vertical" id="generacion">
            <div class="tile is-child box">
                        <figure>
                            <img src="{{proyecto.icono_totem.url}}"
                                 class="icono_medium">
                        </figure>
            </div>
            <div class="tile is-child box">
                        <h5 class="title is-5">{{proyecto}}</h5>
                        <div class="content">
                            {{proyecto.descripcion|safe}}
                        </div>
            </div>
        </div>
        <div class="tile is-parent" id="localizacion">
            
        </div>
        <div class="tile is-parent" id="sesiones">
            
        </div>
        <div class="tile is-parent" id="valores">
            <div class="tile is-child box has-text-centered">
                <h3 class="title is-3">Valores de Inscripción</h3>
                <section id="valores" class="content is-centered table-container">
                    <table class="table is-hoverable is-stripped is-hoverable">
                        <thead>
                            <th>Participante</th>
                            <th>Valor en CLP$</th>
                            <th>Valor en USD$</th>            
                        </thead>
                        <tbody>
                            {% for valor in proyecto.valor.all %}
                            <tr>
                                <td>{{valor.asignacion}}</td>
                                <td>{{valor.precio}}</td>
                                <td>{{valor.usd}}</td>
                            </tr>
                            {% endfor 0%}
                        </tbody>
                    </table>
                </section>
            </div>
        </div>
        <div class="tile is-parent" id="a_formulario">
            <!-- imagen link a inscripción -->
            <div class="tile is-child box">
	          <a  class="button is-rounded link is-large is-link is-active
                       is-fullwidth"
                title="Inscribirse"
                href="{% if inscribirse %}
                       {% url 'inscripcion:persona' object.curso.slug_nombre object.slug_generacion %}
                       {% endif%}">
                {% if inscribirse %}
                Inscribirse en el curso, {{object}}
                {% else %}
                Inscripcion fuera de plazo
                {% endif %}</a>
            </div>
        </div>
    </div>
</div>


{% endblock content_article %}


{% block footer_css %}
<style>
 #show_content{
     background-image:url("{{object.imagen_fondo.url}}");
     background-size:cover;
     background-repeat: no-repeat;
     background-attachment: fixed;
 }
 .icono_medium{
     width:250px;

 }
</style>
{% endblock %}


{% block footer_javascript %}
{{block.super}}
<script>
 let opts_ins = {color:'info', type:"date", read_only:true}
 let inscripciones = {...opts_ins}
 let opts_curso = {color:'alert', type:"date", read_only:true}
 let curso = {...opts_curso}
 {% if object.fecha_inscripcion_inicio %}
 const startDateInscripcion = "{{object.fecha_inscripcion_inicio|date:'m/d/Y'}}";
 inscripciones["startDate"]=new Date(startDateInscripcion);
 {% endif %}
 {% if object.fecha_inscripcion_final %}
 const endDateInscripcion = "{{object.fecha_inscripcion_final|date:'m/d/Y'}}";
 inscripciones["endDate"]=new Date(endDateInscripcion);
 {% endif %}
 {% if object.fecha_inicio %}
 const startDateCurso = "{{object.fecha_inicio|date:'m/d/Y'}}";
 curso["startDate"]=new Date(startDateCurso);
 {% endif %}
 {% if object.fecha_final %}
 const endDateCurso = "{{object.fecha_final|date:'m/d/Y'}}";
 curso["endDate"]=new Date(endDateCurso);
 {% endif %}
 window.addEventListener("DOMContentLoaded", function(event) {
     activate_calendar("inscripcion_dates",
                       ["fecha_inscripcion_inicio",
                        "fecha_inscripcion_final"],
                       inscripciones)
     activate_calendar("clases_dates",["fecha_inicio","fecha_final"],
                       curso)

     /*activa modal de imagenes*/
     var figures=document.querySelectorAll("figure.thumb_imagen.main");
     figures.forEach(figure=>{
         figure.addEventListener("click", event => {
             let element_id=event.target.id;
             let modal_id=element_id+"_modal";
             let modal_el = document.getElementById(modal_id);
             if(modal_el){
                 modal_el.classList.add("is-active");
             }
         })
     });
 });
</script>
{% endblock %}