www_programacion/apps/contenido/urls.py
from django.conf.urls import url
from django.urls import path
from .views import (ApplicationView, ContenidosCursoView, SesionCursoView)
app_name = "contenido"

urlpatterns = [
    path('', ApplicationView.as_view(), name='application'),
    path('curso=<slug:curso>/generacion=<slug:generacion>',
         ContenidosCursoView.as_view(),
         name='curso_main'),
    path(
        'curso=<slug:curso>/generacion=<slug:generacion>/sesion=<int:posicion>',
        SesionCursoView.as_view(),
        name='sesion_main')
]

www_programacion/www_programacion/urls.py
from apps.home.views import (page_not_found, bad_request, permission_denied,
                             server_error)
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('404/', page_not_found),
    path('403/', permission_denied),
    path('400/', bad_request),
    path('500/', server_error),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('cuentas/',
         include('apps.accounts.urls', namespace='accounts'),
         name='accounts'),
    path('perfil/',
         include('apps.perfil_usuario.urls', namespace='perfil'),
         name='perfil'),
    path('', include('apps.home.urls', namespace='home'), name='home'),
    path('pagina/',
         include('apps.pagina.urls', namespace='pagina'),
         name='pagina'),
    path('inscripcion/',
         include('apps.inscripcion.urls', namespace='inscripcion'),
         name='inscripcion'),
    path('contacto/',
         include('apps.contacto.urls', namespace='contacto'),
         name='contacto'),
    path('proyecto/',
         include('apps.proyecto.urls', namespace='proyecto'),
         name='proyecto'),
    path('organizacion/',
         include('apps.organizacion.urls', namespace='organizacion'),
         name='organizacion'),
    path('captcha/', include('captcha.urls'), name='captcha'),
    path("admin_group/",
         include('apps.admin_group.urls', namespace='admin_group'),
         name='admin_group'),
    path('groups_manager/',
         include('groups_manager.urls', namespace='groups_manager'),
         name='groups_manager'),
    path("contenido/",
         include("apps.contenido.urls", namespace='contenido'),
         name='contenido')
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

www_programacion/apps/contenido/models.py
from django.utils.functional import lazy
from datetime import time
from django.db import models
from django.conf import settings
if 'sqlite3' in settings.DATABASES["default"]["ENGINE"]:
    from jsonfield import JSONField
else:
    from django.contrib.postgres.fields import JSONField
# Create your models here.
#from apps.proyecto.models import Proyecto

from django.db.models.signals import post_save
from django.dispatch import receiver

from datetime import datetime as dt
from django.utils.timezone import datetime
from django.utils.dateparse import parse_date
from django.utils.timezone import is_aware, make_aware
from .validators import validate_file_extension
from .functions import load_data, get_date, get_time
import os
from django.utils.text import slugify
from groups_manager.models import (Group, Member, GroupEntity, GroupMember,
                                   GroupMemberRole)
from django.contrib.auth.models import User

from apps.proyecto.models import Proyecto
from django.urls import reverse


def file_upload_programa(instance, filename):
    try:
        proyecto = instance.proyecto
        curso = proyecto.curso
        if getattr(curso, 'slug', None):
            curso_slug = curso.slug
        else:
            curso_slug = slugify(curso)
        if getattr(proyecto, 'slug', None):
            generacion = proyecto.slug
        else:
            generacion = slugify(proyecto)
        return f"{curso_slug}/{generacion}/programa/{filename}"
    except Exception as ex:
        raise ex


class ContenidosProyecto(models.Model):
    """
    JSON debe contener las rutas al html principal de cada sesión
    Por cada 'save' de contenidos proyecot se debe crear de manera automatica
    las sesiones descritas en parametros
    """
    def default_json():
        DEFAULT_JSON = {
            'sesiones': {
                1: {
                    "posicion": 1,
                    "fecha": 'd/m/Y',
                    "titulo": "Nombre sesión",
                    "resumen": "resumen"
                }
            }
        }
        return DEFAULT_JSON

    proyecto = models.OneToOneField(Proyecto,
                                    related_name='contenido',
                                    on_delete=models.SET_NULL,
                                    null=True)
    parametros = JSONField(default=default_json)
    programa = models.FileField(upload_to=file_upload_programa,
                                null=True,
                                max_length=1200,
                                blank=True,
                                validators=[validate_file_extension])
    actualizar = models.BooleanField(default=True)
    max_notificaciones = models.PositiveIntegerField(default=3)
    notificar = models.BooleanField(default=True)
    cantidad_clases = models.PositiveIntegerField(default=10)

    def __repr__(self):
        return f"Contenidos|{self.proyecto.curso}|{self.proyecto}"

    def __str__(self):
        return f"Contenidos|{self.proyecto.curso}|{self.proyecto}"

    def save(self, *args, **kwargs):
        self.merge_params()
        instance = super().save(*args, **kwargs)

    @property
    def programa_ext(self):
        if isinstance(self.programa.name, str):
            ext = self.programa.name.split(".")[-1]
            return ext
        else:
            return ""

    def merge_params(self):
        """
        Update new information from CSV to field
        """
        clase = type(self)
        anterior = None
        if self.id:
            anterior = clase.objects.get(id=self.id)
        #
        if self.programa_ext == 'csv':
            if anterior:
                if self.programa != anterior.programa or self.actualizar:
                    self.load_data()
            else:
                self.load_data()

    def load_data(self):
        """
        Lee csv, cada fila será un dict
        Revisa si el dato en csv existe, entonces lo reemplaza en json
        """
        if 'sesiones' not in self.parametros:
            self.parametros["sesiones"] = {}
        fields = ["posicion", "fecha", "titulo", "resumen", "hora", "modo"]
        sesiones = load_data(self.programa)
        self.parametros["sesiones"].update(sesiones)


@receiver(post_save, sender=ContenidosProyecto)
def create_sessions(sender, instance, created, raw, using, **kwargs):
    sessions = instance.parametros.get("sesiones", {})
    print("Sesiones->", sessions)
    for position, session_param in sessions.items():
        print("Position", position)
        sessions = Sesion.objects.filter(contenidos_proyecto=instance)
        if sessions.count() <= instance.cantidad_clases:
            _date = session_param.get('fecha')
            _hora = session_param.get('hora')
            print("Date", _date, "Hora", _hora)
            session_param["fecha"] = get_date(_date)
            session_param["hora"] = get_time(_hora)
            print("SESSION PARAM", session_param)
            session, creada = Sesion.objects.get_or_create(
                contenidos_proyecto=instance, **session_param)


class SettingsNotificacion(models.Model):
    """
    Notificaciones configuradas para el usuario
    """
    MENSAJE = """
    Recuerda {{nombre_completo}}, a las {{hora}} de hoy {{dia}}
    tienes la clase del curso {{curso}}.
    """
    VARIABLES = """
    nombre_completo :: tu nombre
    hora :: hora de inicio de clases
    dia :: dia de la clase
    curso :: nombre del curso 
    """
    HORA_ENVIO = time(8)
    TIEMPO = 60
    EMAIL = '@'
    TELEGRAM = 'TG'
    CHOICES = [(EMAIL, "E-mail"), (TELEGRAM, "telegram")]
    contenidos = models.ForeignKey(ContenidosProyecto,
                                   related_name='notificaciones',
                                   on_delete=models.CASCADE)
    medio = models.CharField(max_length=10, choices=CHOICES, default=EMAIL)
    mensaje = models.TextField(default=MENSAJE)
    repetir = models.BooleanField(default=False)
    periodo_tpo = models.PositiveIntegerField(default=TIEMPO)
    horas_antes = models.PositiveIntegerField(default=10)
    hora_envio = models.TimeField(default=HORA_ENVIO)
    miembro = models.ForeignKey(Member,
                                related_name='notificaciones',
                                on_delete=models.CASCADE,
                                null=True,
                                blank=True)


class Sesion(models.Model):
    """
    Por ContenidoProyecto : Sesiones

    unique_key: ["sesion", "posicion"]

    Al guardar-> Crear tareas programadas de:
    envíar emails a estudiantes  y miembros
    tb. Telegram msg o wsp

    Que se muestre la opcion en perfil: de manera general
    settings: configuración por sesion por defecto 1 email

    Limitar según la cantidad y valores disponibles:
    cont_proyecto = ?
    ids_sesion = {s.id for s in cont_proyecto.sesiones.all()}
    ids_av = {i+1 for i in range(cont_proyecto.cantidad_clases)}
    available = ids_av - ids_sesion
    """
    TIME_INICIO = get_time("18:00:00")
    CHOICE_MODE = [("O", "online"), ("P", "presencial"), ("OP", "mixto")]
    CHOICES_DICT = dict(CHOICE_MODE)
    posicion = models.PositiveIntegerField(default=0, blank=True, null=True)
    contenidos_proyecto = models.ForeignKey(ContenidosProyecto,
                                            related_name='sesiones',
                                            on_delete=models.SET_NULL,
                                            null=True)
    titulo = models.CharField(max_length=250)
    slug_titulo = models.SlugField(null=True, blank=True, max_length=250)
    fecha = models.DateField()
    hora = models.TimeField(default=TIME_INICIO)
    modo = models.CharField(max_length=2, choices=CHOICE_MODE, default='O')
    url_online = models.URLField(max_length=1000,
                                 default='https://www.cursodeprogramacion.cl')
    lugar = models.CharField(max_length=100, default="Santiago, Chile")
    realizada = models.BooleanField(default=False)
    resumen = models.TextField()

    def __repr__(self):
        return f"{self.posicion}:{self.titulo}"

    def __str__(self):
        return f"{self.posicion}:{self.titulo}"

    def save(self, *args, **kwargs):
        self.slug_titulo = slugify(self.titulo)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        posicion = self.posicion
        curso = self.contenidos_proyecto.proyecto.curso.slug
        generacion = self.contenidos_proyecto.proyecto.slug
        kwargs = {
            "posicion": posicion,
            "curso": curso,
            "generacion": generacion
        }
        return reverse('contenido:sesion_main', kwargs=kwargs)

    class Meta:
        ordering = ["posicion"]


def file_upload(instance, filename):
    try:
        proyecto = instance.sesion.contenidos_proyecto.proyecto
        curso = proyecto.curso.slug_nombre
        generacion = proyecto.slug_generacion
        sesion = instance.sesion.slug_titulo
        tipo = instance.tipo
        if proyecto:
            return f"{curso}/{generacion}/{sesion}/{tipo}/{filename}"
        else:
            return f"proyecto_perdido/{tipo}/{filename}"
    except Exception as ex:
        raise ex


def file_upload_torrent(instance, filename):
    try:
        proyecto = instance.sesion.contenidos_proyecto.proyecto
        curso = proyecto.curso.slug_nombre
        generacion = proyecto.slug_generacion
        sesion = instance.sesion.slug_titulo
        tipo = "torrent"
        if proyecto:
            return f"{curso}/{generacion}/{sesion}/{tipo}/{filename}"
        else:
            return f"proyecto_perdido/{tipo}/{filename}"
    except Exception as ex:
        raise ex


class Contenido(models.Model):
    """
    Por sesión:  guia, ejercicio
    """
    CLASE = 'CL'
    EJERCICIO = 'EJ'
    CONTENIDO_CHOICES = [(CLASE, "clase"), (EJERCICIO, "ejercicio")]
    DICT_CHOICES = dict(CONTENIDO_CHOICES)

    sesion = models.ForeignKey(Sesion,

www_programacion/apps/contenido/forms.py
from django import forms


class SearchContentForm(forms.Form):
    busqueda = forms.CharField(label='Búsqueda', max_length=200)

www_programacion/apps/contenido/views.py
from django.shortcuts import render
from django.views.generic import FormView
from django.views.generic import ListView
from django.views.generic import DetailView

from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import SearchContentForm
from .models import (ContenidosProyecto, Sesion, Contenido)
from apps.proyecto.models import Proyecto
from django.shortcuts import get_object_or_404


def app_menu():
    menu = {}
    return menu


class ContenidoBase:
    app_active = 'Contenido'

    def menu(self):
        this_menu = app_menu()
        return this_menu


# Create your views here.
# TODO: add ListView -> post aggregar modelo
class ApplicationView(LoginRequiredMixin, ContenidoBase, FormView):
    """
    Formulario para buscar contenidos dentro de las sesiones
    - Busca en cada curso que la persona tiene acceso
    - Busca coincidencias en títulos, tags y contenidos?
    - Los resultados los muestra aquí mismo en una tabla de resulados
    """
    template_name = 'contenido/app.dj.html'
    form_class = SearchContentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["menu"] = self.menu()
        context["menu_title"] = self.app_active.capitalize()
        return context


class ContenidosCursoView(LoginRequiredMixin, ContenidoBase, DetailView):
    """
    En base al curso-generacion
    Encuentra 'ContenidosCurso'
    Dado que es una relación 1:1
    """
    template_name = 'contenido/main.dj.html'
    model = ContenidosProyecto
    slug_field = 'proyecto'
    slug_url_kwarg = 'generacion'

    def get(self, request, *args, **kwargs):
        self.url_kwargs = kwargs
        return super().get(request, *args, **kwargs)

    def get_object(self, **kwargs):
        generacion = self.url_kwargs.get('generacion')
        self.proyecto = Proyecto.objects.get(slug_generacion=generacion)
        self.object = get_object_or_404(ContenidosProyecto,
                                        proyecto=self.proyecto)
        return self.object

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["menu"] = self.menu()
        context["menu_title"] = self.app_active.capitalize()
        context["proyecto"] = self.proyecto
        context["curso"] = self.proyecto.curso
        context["menu"] = self.menu()
        context["bread"] = "general"
        return context


class SesionCursoView(LoginRequiredMixin, ContenidoBase, DetailView):
    template_name = 'contenido/sesion.dj.html'
    model = Sesion
    slug_field = 'proyecto'
    slug_url_kwarg = 'generacion'

    def get(self, request, *args, **kwargs):
        self.url_kwargs = kwargs
        return super().get(request, *args, **kwargs)

    def get_object(self, **kwargs):
        generacion = self.url_kwargs.get('generacion')
        posicion = self.url_kwargs.get('posicion')
        self.proyecto = Proyecto.objects.get(slug_generacion=generacion)
        contenidos = ContenidosProyecto.objects.get(proyecto=self.proyecto)
        self.contenidos = contenidos
        sesion = Sesion.objects.get(posicion=posicion,
                                    contenidos_proyecto=contenidos)
        return sesion

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["menu"] = self.menu()
        context["menu_title"] = self.app_active.capitalize()
        context["proyecto"] = self.proyecto
        context["curso"] = self.proyecto.curso
        context["menu"] = self.menu()
        context["clase"] = self.object.contenidos.filter(tipo="CL")
        context["ejercicio"] = self.object.contenidos.filter(tipo="EJ")
        context["bread"] = "sesion"
        context["siguiente"] = None
        context["anterior"] = None
        if self.object.posicion < self.contenidos.cantidad_clases:
            context["siguiente"] = Sesion.objects.get(
                contenidos_proyecto=self.contenidos,
                posicion=self.object.posicion + 1)
        if self.object.posicion > 1:
            context["anterior"] = Sesion.objects.get(
                contenidos_proyecto=self.contenidos,
                posicion=self.object.posicion - 1)
        return context

www_programacion/apps/contenido/templates/contenido/app.dj.html
{% extends 'contenido/base.dj.html' %}
<!-- Permitir el uso de estaticos css js -->
{% load static %}


{% block content_contenido %}
{% include 'contenido/search.dj.html' %}
{% endblock%}

www_programacion/apps/contenido/templates/contenido/base.dj.html
{% extends 'base.dj.html' %}
<!-- Permitir el uso de estaticos css js -->
{% load static %}

{% block title %}
Contenido | {{SITE_NAME}}
{% endblock %}

{% block breadcrumbs %}
{{block.super}}
<li>
    <a href="{% url 'contenido:application' %}">Contenido</a>
</li>
{% endblock breadcrumbs %}


{% block sidebar_left %}
<aside class="sticky">
    {% include 'contenido/main_menu.dj.html' %}
</aside>
{% endblock sidebar_left %}

{% block content_article %}
{% block content_contenido %}
{% endblock%}
{% endblock%}

www_programacion/apps/contenido/templates/contenido/de_sesion.dj.html
<!-- sesion, tipo, video_url, resumen, documento, date_time, date_time_updated,-->
<!-- guia -->

<div class="content">
    <!-- variable: contenido -->
    {% for contenido in contenidos.all %}
    {% if contenido %}
    <div class="tile box">
        <div class="tile is-6">
            <p>Creado en {{contenido.date_time}}</p>
        </div>
        <div class="tile is-6">
            <p>Última actualización {{contenido.date_time_updated}}</p>
        </div>
    </div>
    <div class="video">
        <div id="player_{{tipo}}">
        </div>
        <div class="is-hidden">
            {% if contenido.torrent %}
            <input id="magnet_link_{{tipo}}"
                   value="{{MEDIA_URL}}{{contenido.torrent.url}}">
            {% endif %}
        </div>
        <div class="download">
            <a href="{{contenido.video_url}}">Video Torrent</a>
        </div>
    </div>
    <p>{{contenido.resumen|safe}}</p>
    <div>{% if contenido.documento %}
        <a href="{{contenido.documento.url}}">Descargar</a>
        {% endif %}
    </div>
    {% endif %}
    {% endfor %}
</div> 

www_programacion/apps/contenido/templates/contenido/main.dj.html
{% extends 'contenido/base.dj.html' %}
<!-- Permitir el uso de estaticos css js -->
{% load static %}

{% block breadcrumbs %}
{{block.super}}
<li class="{% if bread == "general" %}is-active{% endif %}">
    <a href="{% url 'contenido:curso_main' curso=curso.slug generacion=proyecto.slug %}">{{curso}}|{{proyecto}}</a>
</li>
{% endblock breadcrumbs %}


{% block content_contenido %}
<!-- menu y bloque de contenidos -->
<!-- menu debe tener: info, ultima sesion, descargas, ademas ADMIN si se es-->
<!-- admin de grupo -->
<!-- bloque de contenidos info de curso -->
<!-- abajo lista de sesiones -->
<div class="tile is-parent">
    <!-- info del curso -->
    <!-- object es: ContenidosCurso -->
    <!-- tiene 1:1 con proyecto -->
    <div class="tile is-child box">
        <h3 class="title is-3">
            {{object.proyecto.curso}}|{{object.proyecto}}
        </h3>
        <div class="tile">
            <!-- imagen -->
            <div class="tile is-child is-4">
                <figure>
                <img id="imagen_curso"
                     src="{{object.proyecto.curso.imagen.url}}">
                </figure>
            </div>
            <!-- resumen -->
            <div class="tile is-child">
                {{object.proyecto.curso.descripcion|truncatewords_html:100|safe}}
            </div>
        </div>

    </div>


</div>
<div class="tile is-parent is-vertical">
    <!-- lista de sesiones -->
    <div class="tile is-child box">
        <h4 class="title is-4">Sesiones</h4>
        <table class="table  is-hoverable is-stripped  is-fullwidth">
            <thead>
                <tr>
                    <th>Posición</th>
                    <th>Título</th>
                    <th>Fecha</th>
                    <th>Hora</th>
                    <th>Acción</th>
                </tr>

            </thead>
            <tbody>
        {% for sesion in object.sesiones.all %}
                <tr>
                    <td>{{sesion.posicion}}</td>
                    <td>{{sesion.titulo}}</td>
                    <td>{{sesion.fecha}}</td>
                    <td>{{sesion.hora}}</td>
                    <td>
                        <a href="{% if curso and proyecto %}
{% url 'contenido:sesion_main' curso=curso.slug generacion=proyecto.slug posicion=sesion.posicion %}
                                 {% endif%}">
                            Ver</a>
                    </td>
                </tr>
        {% endfor %}
            </tbody>
    </table>
    </div>
</div>
{% endblock%}


{% block footer_css %}
<style>
 #imagen_curso{
     width:300px;
     height:200px;
 }


</style>
{% endblock %}

www_programacion/apps/contenido/templates/contenido/main_menu.dj.html
<h4 class="title is-4">
    <a href="{% url 'contenido:application' %}">
        {{menu_title}}</a>
</h4>
<section class="accordions">
    {% for app, group in menu.items %}
    <div class="accordion {% if app == app_active %}is-active{% endif%} is-success">
        <p class="accordion-header toggle">
            {{app}}
        </p>
        <ul class="accordion-body">
            {% for elem in group %}
            <li class="accordion-content">{{elem.html|safe}}</li>
            {% endfor %}
        </ul>
    </div>
    {% endfor %}
</section>

www_programacion/apps/contenido/templates/contenido/search.dj.html
{% load static %}
{% load widget_tweaks %}
<form action="{{request.get_full_path}}"
      method="post"
      class="form"
      id="search_form">
    {% csrf_token %}
    <div  class="field has-addons" id="field_busqueda">
            <div class="control is-expanded">
                {% render_field form.busqueda class+="input" %}
                <span class="help is-invalid">{{ form.busqueda.errors }}</span>
            </div>
    <div class="control">
        <button type="submit" class="button
                      is-primary is-fullwidth">Buscar</button>
    </div>
    </div>
</form>

www_programacion/apps/contenido/templates/contenido/sesion.dj.html
{% extends 'contenido/main.dj.html' %}
<!-- Permitir el uso de estaticos css js -->
{% load static %}

<!-- Contenidos de sesion -->

{% block breadcrumbs %}
{{block.super}}
<li class="{% if bread == "sesion" %}is-active{% endif %}">
    {{object.titulo}}({{object.posicion}})
</li>
{% endblock breadcrumbs %}

<!-- tabs -->
<!-- contenidos de clase -->
<!-- contenidos de ejercicios -->
<!-- info de profesores -->

{% block content_contenido %}
<div class="tile is-parent is-vertical">
    <div class="tile box">
        <div class="tile is-child is-6 box has-text-left">
            {% if anterior%}
            <a href="{{anterior.get_absolute_url}}"><i class="fa fa-long-arrow-alt-left" aria-hidden="true"></i> {{anterior.titulo}}</a>
            {% endif %}</div>
        <div class="tile is-child is-6 box has-text-right">
            {% if siguiente %}
            <a href="{{siguiente.get_absolute_url}}">
                {{siguiente.titulo}} <i class="fa fa-long-arrow-alt-right" aria-hidden="true"></i></a>
            {% endif %}
        </div>
    </div>
    <div class="tile is-child box">
        {{object.resumen}}
    </div>
    <div class="tile is-child box">
    <div class="tabs is-centered">
        <ul>
            <li class="is-active" onclick="show('clase')" id="tab_clase"><a>Clase</a></li>
            <li class="" onclick="show('ejercicio')" id="tab_ejercicio"><a>Ejercicio</a></li>
            <li class="" onclick="show('profesores')" id="tab_profesores"><a>Profesor@s</a></li>
        </ul>
    </div>
    <div class="content" id="clase">
        <h4 clas="title is-4">Clase {{object.titulo}}</h4>
        {% include 'contenido/de_sesion.dj.html' with contenidos=clase tipo="clase" %}
    </div>
    <div class="content is-hidden" id="ejercicio">
        <h4 clas="title is-4">Ejercicio {{object.titulo}}</h4>
        {% include 'contenido/de_sesion.dj.html' with contenidos=ejercicio tipo="ejercicio" %}
        </div>
        <div class="content is-hidden" id="profesores">
            <h4 clas="title is-4">Profesores</h4></div>
    </div>
</div>
{% endblock %}


{% block footer_javascript %}
<script src="{% static 'contenido/js/webtorrent.min.js' %}"></script>
<script>
 let is_hidden='is-hidden';
 let is_active='is-active';
 let seleccion="clase";
 let players = ["curso","ejercicio"];
 function show(idname){
     let tab = document.getElementById("tab_"+idname);
     let tab_pasada = document.getElementById("tab_"+seleccion);
     let pasada = document.getElementById(seleccion);
     let cambio = document.getElementById(idname);
     if (seleccion!=idname){
         if (!pasada.classList.contains(is_hidden)){
             pasada.classList.add(is_hidden);
             tab_pasada.classList.remove(is_active);
         }
         if (cambio.classList.contains(is_hidden)){
             cambio.classList.remove(is_hidden);
             tab.classList.add(is_active);
         }
         if (name in players){
             deactivate_player(seleccion)
             activate_player(idname)

         }
         seleccion=idname;
     }
 }
 /*
    Activate video torrent
  */
 let client=new WebTorrent();
 let active_torrent=null;

 function activate_player(name){
     let magnet_link=document.getElementById("magnet_link_"+name);
     let elem_player=document.getElementById("player_"+name);
     if (magnet_link){
         let url = magnet_link.value;
         console.log("URL Torrent", url);
         client.add(url, function (torrent){
             let file= torrent.files.find(function(file){
                 return file.name.endsWith(".mp4")
             }
             )
             var video=document.createElement(video);
             video.controls=true;
             elem_player.appendChild(video);
             file.appendTo("#player_"+name);
             })
     }

 }
             function deactivate_player(name){

             }
             activate_player(seleccion)

</script>
{% endblock %}



{% block footer_css %}
<link rel="stylesheet" href="{% static 'contenido/css/video.css' %}">
{% endblock %}