www_programacion/apps/proyecto/urls.py
from django.conf.urls import url
from django.urls import path

from apps.proyecto import views
from .feed import LatestProjects
app_name = 'proyecto'

urlpatterns = [
    path('', views.ProjectAppView.as_view(), name='application'),
    path('mis_cursos/', views.MisCursos.as_view(), name='my_courses'),
    # curso
    path('curso/listar', views.CourseListView.as_view(), name='course_list'),
    path('curso/crear', views.CourseCreateView.as_view(),
         name='course_create'),
    path('curso/nombre=<slug:slug_nombre>',
         views.CourseDetailView.as_view(),
         name='course_detail'),
    path('curso/editar/nombre=<slug:slug_nombre>',
         views.CourseEditView.as_view(),
         name='course_edit'),
    path('curso/borrar/nombre=<slug:slug_nombre>',
         views.CourseDeleteConfirmView.as_view(),
         name='course_delete'),
    # project
    path('proyecto/listar',
         views.ProjectListView.as_view(),
         name='project_list'),
    path('proyecto/crear',
         views.ProjectCreateView.as_view(),
         name='project_create'),
    path('proyecto/show=<slug:slug_curso>/gen=<slug:slug_generacion>',
         views.ProjectCourseGenerationView.as_view(),
         name='course_generation'),
    path('proyecto/<slug:slug_curso>/<slug:slug_generacion>',
         views.ProjectDetailView.as_view(),
         name='project_detail'),
    path('proyecto/editar/nombre=<slug:slug_generacion>',
         views.ProjectEditView.as_view(),
         name='project_edit'),
    path('proyecto/borrar/nombre=<slug:slug_generacion>',
         views.ProjectDeleteConfirmView.as_view(),
         name='project_delete'),
    path('feed/', LatestProjects()),
    # email templates
    path('emails/listar', views.EmailsListView.as_view(), name='emails_list'),
    path('emails/crear',
         views.EmailsCreateView.as_view(),
         name='emails_create'),
    path('emails/editar/<int:pk>',
         views.EmailsEditView.as_view(),
         name='emails_edit'),
    path('emails/<int:pk>',
         views.EmailsDetailView.as_view(),
         name='emails_detail'),
    path('emails/borrar/<int:pk>',
         views.EmailsDeleteConfirmView.as_view(),
         name='emails_delete'),
    path('emails/preview/<int:pk>/field=<slug:field>',
         views.EmailsPreviewView.as_view(),
         name='emails_preview'),
    # clasification
    path('clasificacion/listar',
         views.ClasificationListView.as_view(),
         name='clasification_list'),
    path('clasificacion/crear',
         views.ClasificationCreateView.as_view(),
         name='clasification_create'),
    path('clasification/nombre=<slug:slug_tipo>',
         views.ClasificationDetailView.as_view(),
         name='clasification_detail'),
    path('clasificacion/editar/nombre=<slug:slug_tipo>',
         views.ClasificationEditView.as_view(),
         name='clasification_edit'),
    path('clasificacion/borrar/nombre=<slug:slug_tipo>',
         views.ClasificationDeleteConfirmView.as_view(),
         name='clasification_delete'),
    # valor
    path('valor/listar',
         views.CourseValueListView.as_view(),
         name='coursevalue_list'),
    path('valor/crear',
         views.CourseValueCreateView.as_view(),
         name='coursevalue_create'),
    path('valor/id=<int:pk>',
         views.CourseValueDetailView.as_view(),
         name='coursevalue_detail'),
    path('valor/editar/id=<int:pk>',
         views.CourseValueEditView.as_view(),
         name='coursevalue_edit'),
    path('valor/borrar/id=<int:pk>',
         views.CourseValueDeleteConfirmView.as_view(),
         name='coursevalue_delete'),
]

www_programacion/www_programacion/urls.py
from apps.home.views import (page_not_found, bad_request, permission_denied,
                             server_error)
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('404/', page_not_found),
    path('403/', permission_denied),
    path('400/', bad_request),
    path('500/', server_error),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('cuentas/',
         include('apps.accounts.urls', namespace='accounts'),
         name='accounts'),
    path('perfil/',
         include('apps.perfil_usuario.urls', namespace='perfil'),
         name='perfil'),
    path('', include('apps.home.urls', namespace='home'), name='home'),
    path('pagina/',
         include('apps.pagina.urls', namespace='pagina'),
         name='pagina'),
    path('inscripcion/',
         include('apps.inscripcion.urls', namespace='inscripcion'),
         name='inscripcion'),
    path('contacto/',
         include('apps.contacto.urls', namespace='contacto'),
         name='contacto'),
    path('proyecto/',
         include('apps.proyecto.urls', namespace='proyecto'),
         name='proyecto'),
    path('organizacion/',
         include('apps.organizacion.urls', namespace='organizacion'),
         name='organizacion'),
    path('captcha/', include('captcha.urls'), name='captcha'),
    path("admin_group/",
         include('apps.admin_group.urls', namespace='admin_group'),
         name='admin_group'),
    path('groups_manager/',
         include('groups_manager.urls', namespace='groups_manager'),
         name='groups_manager'),
    path("contenido/",
         include("apps.contenido.urls", namespace='contenido'),
         name='contenido')
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

www_programacion/apps/proyecto/forms.py
from django import forms
from django_json_widget.widgets import JSONEditorWidget
from .models import EmailTemplates, Curso, Proyecto


class CursoForm(forms.ModelForm):
    class Meta:
        model = Curso
        fields = [
            "nombre", "imagen", "resumen", "descripcion", "clasificacion",
            "usuario"
        ]
        widgets = {'usuario': forms.HiddenInput}


class ProyectoForm(forms.ModelForm):
    fecha_inscripcion_inicio = forms.DateField(
        widget=forms.HiddenInput(attrs={"id": "fecha_inscripcion_inicio"}),
        input_formats=['%d/%m/%Y'])
    fecha_inscripcion_final = forms.DateField(
        widget=forms.HiddenInput(attrs={"id": "fecha_inscripcion_final"}),
        input_formats=['%d/%m/%Y'])
    fecha_inicio = forms.DateField(
        widget=forms.HiddenInput(attrs={"id": "fecha_inicio"}),
        input_formats=['%d/%m/%Y'])
    fecha_final = forms.DateField(
        widget=forms.HiddenInput(attrs={"id": "fecha_final"}),
        input_formats=['%d/%m/%Y'])

    class Meta:
        model = Proyecto
        fields = [
            "curso", "valor", "generacion", "imagen_totem", "icono_totem",
            "afiche", "imagen_fondo", "resumen", "descripcion", "fecha_inicio",
            "fecha_final", "fecha_inscripcion_inicio",
            "fecha_inscripcion_final", "usuario"
        ]
        widgets = {'usuario': forms.HiddenInput}


class EmailTemplatesForm(forms.ModelForm):
    class Meta:
        model = EmailTemplates

        fields = ["proyecto", "parametros"] + list(
            map(lambda x: f"inscripcion_{x}", [
                "exitosa_usuario", "exitosa_admin", "rechazo", "acepta",
                "result_admins"
            ]))

        widgets = {'parametros': JSONEditorWidget(width="600px")}

www_programacion/apps/proyecto/views.py
from .models import get_member
from django.utils.timezone import datetime  # important if using timezones
from django.contrib.auth.models import User
from .forms import EmailTemplatesForm, CursoForm, ProyectoForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, HttpResponseRedirect
from networktools.library import my_random_string
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from datetime import datetime as dt, date, time
from files.functions.links import LinkData
from apps.inscripcion.models import Inscripcion, ChequeoCodigo
from apps.proyecto.models import (Proyecto, Curso, Clasificacion, ValorCurso,
                                  EmailTemplates)
from apps.home.views import menu_nav
from apps.admin_group.functions import my_cursos, my_proyectos, get_member
"""
Generic Views
"""
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic import TemplateView
from django.views.generic import CreateView
from django.views.generic import DeleteView
from django.views.generic import UpdateView
"""
app imports
"""
"""
Other imports
"""
# from django.contrib.messages.views import SuccessMessageMixin


def app_menu():
    menu = {
        "Clasificación": [
            LinkData("Listar",
                     "proyecto:clasification_list",
                     model="clasificacion",
                     perms=["view"]),
            LinkData("Crear",
                     "proyecto:clasification_create",
                     model="clasificacion",
                     perms=["add"]),
        ],
        "Curso": [
            LinkData("Listar",
                     "proyecto:course_list",
                     model="curso",
                     perms=["view"]),
            LinkData("Crear",
                     "proyecto:course_create",
                     model="curso",
                     perms=["add"]),
        ],
        "Proyecto": [
            LinkData("Listar",
                     "proyecto:project_list",
                     model="proyecto",
                     perms=["view"]),
            LinkData("Crear",
                     "proyecto:project_create",
                     model="proyecto",
                     perms=["add"]),
        ],
        "Email": [
            LinkData("Listar",
                     "proyecto:emails_list",
                     model="emailtemplates",
                     perms=["view"]),
            LinkData("Crear",
                     "proyecto:emails_create",
                     model="emailtemplates",
                     perms=["add"]),
        ],
        "Valor": [
            LinkData("Listar",
                     "proyecto:coursevalue_list",
                     model="valorcurso",
                     perms=["view"]),
            LinkData("Crear",
                     "proyecto:coursevalue_create",
                     model="valorcurso",
                     perms=["add"]),
        ],
    }
    return menu


"""
Base :::
"""


class ProjectBase:
    app_active = "Proyecto"

    def menu(self):
        this_menu = app_menu()
        return this_menu


"""
Project
"""


class ProjectAppView(LoginRequiredMixin, ProjectBase, TemplateView):
    template_name = 'proyecto/app.dj.html'

    def get_context_data(self, *args, **kwargs):
        kwargs = super().get_context_data(**kwargs)
        kwargs.update({
            'menu_nav': menu_nav,
            "menu": self.menu(),
            "app_active": self.app_active
        })
        return kwargs


class ProjectListView(LoginRequiredMixin, ProjectBase, ListView):
    """
    TODO:
    Listar proyectos de curso activos para inscripción
    Configurar alertas:
    AZUL-VERDE-AMARILLO-ROJO
    >1mes,1mes,2sem,1sem
    """
    template_name = 'proyecto/proyecto/list.dj.html'
    model = Proyecto
    today_min = dt.combine(date.today(), time.min)

    def get_context_data(self, *args, **kwargs):
        today_min = self.today_min
        kwargs = super().get_context_data(**kwargs)
        proyectos_inscripcion_activa = Proyecto.objects.filter(
            Q(fecha_inscripcion_inicio__lte=today_min)
            & Q(fecha_inscripcion_final__gte=today_min))
        proyectos_en_proceso = Proyecto.objects.filter(
            Q(fecha_inicio__lte=today_min) & Q(fecha_final__gte=today_min))
        proyectos_realizados = Proyecto.objects.filter(
            fecha_final__lt=today_min)
        proyectos = {
            'inscripcion_activa': proyectos_inscripcion_activa,
            'proceso': proyectos_en_proceso,
            'realizados': proyectos_realizados,
        }
        kwargs['proyectos'] = proyectos
        kwargs.update({
            'menu_nav': menu_nav,
            "menu": self.menu(),
            "app_active": self.app_active
        })
        return kwargs


class ProjectDetailView(LoginRequiredMixin, ProjectBase, DetailView):
    model = Proyecto
    template_name = 'proyecto/proyecto/detail.dj.html'
    slug_field = 'slug_generacion'
    slug_url_kwarg = 'slug_generacion'

    def menu(self):
        this_menu = super().menu()
        module = this_menu.get(self.app_active)
        kwargs = {"slug_generacion": self.object.slug_generacion}
        if self.member.has_perm('change_proyecto', self.object):
            update = LinkData("Editar",
                              "proyecto:project_edit",
                              opts={
                                  "kwargs": kwargs,
                              },
                              css_class="has-text-primary",
                              model="proyecto",
                              perms=["change"])
            module.append(update)
        if self.member.has_perm('delete_proyecto', self.object):
            delete = LinkData("Borrar",
                              "proyecto:project_delete",
                              opts={
                                  "kwargs": kwargs,
                              },
                              css_class="has-text-danger",
                              model="proyecto",
                              perms=["delete"])
            module = this_menu.get(self.app_active)
            module.append(delete)
        if self.object.group and self.member.has_perm('add_member',
                                                      self.object.group):
            add_member = LinkData(
                "Agregar Miembro",
                "admin_group:member2group_project",
                opts={"kwargs": {
                    "pk": self.object.group.id
                }},
                css_class="has-text-info")
            module.append(add_member)
        return this_menu

    def get_context_data(self, *args, **kwargs):
        user = self.request.user
        self.member = get_member(user)
        kwargs = super().get_context_data(**kwargs)
        kwargs.update({
            'menu_nav': menu_nav,
            "menu": self.menu(),
            "app_active": self.app_active,
            "main_group": self.object.group,
            "tipo": "project",
            "member": self.member
        })
        if self.object.group:
            kwargs.update({
                "members": {
                    "responsables":
                    self.object.group.member_creador_y_responsables(),
                    "profesores":
                    self.object.group.member_profesores(),
                    "ayudantes":
                    self.object.group.member_ayudantes(),
                    "estudiantes":
                    self.object.group.member_estudiantes(),
                    "postulantes": [],
                    "rechazados": [],
                },
                "groups": {
                    "responsables":
                    self.object.group.get_creador_y_responsables(),
                    "profesores": self.object.group.get_profesores(),
                    "ayudantes": self.object.group.get_ayudantes(),
                    "estudiantes": self.object.group.get_estudiantes(),
                },
            })
        return kwargs


class ProjectCourseGenerationView(ProjectBase, DetailView):
    model = Proyecto
    template_name = 'proyecto/proyecto/show.dj.html'
    slug_field = 'slug_generacion'
    slug_url_kwarg = 'slug_generacion'

    def menu(self):
        kwargs = {
            "slug_generacion": self.object.slug_generacion,
            "slug_curso": self.object.curso.slug_nombre
        }
        this_menu = {
            "Índice": [
                LinkData("El curso",
                         "proyecto:course_generation",
                         opts={"kwargs": kwargs},
                         go_to="sobre_curso"),
                LinkData("Fechas",
                         "proyecto:course_generation",
                         opts={"kwargs": kwargs},
                         go_to="fechas_importantes"),
                LinkData("Generación",
                         "proyecto:course_generation",
                         opts={"kwargs": kwargs},
                         go_to="generacion"),
                LinkData("Localización",
                         "proyecto:course_generation",
                         opts={"kwargs": kwargs},
                         go_to="localizacion"),
                LinkData("Quienes enseñan",
                         "proyecto:course_generation",
                         opts={"kwargs": kwargs},
                         go_to="profesores"),
                LinkData("Sesiones",
                         "proyecto:course_generation",
                         opts={"kwargs": kwargs},
                         go_to="sesiones"),
                LinkData("Valores",
                         "proyecto:course_generation",
                         opts={"kwargs": kwargs},

www_programacion/apps/proyecto/templates/proyecto/valor_curso/confirm_delete.dj.html
{% extends 'proyecto/delete_base.dj.html' %}
{% load widget_tweaks %}

{% block form_delete%}
<h2 class="title is-2">
    <i class="fa fa-groups-manager-group"></i> Borrar 'Valor de Curso'
</h2>

<div class="bs-callout bs-callout-danger">
    <h3 class="title is-3">{{ object }}</h3>
    <p>¿Estás segur@ que deseas borrar este valor?</p>
    <p>Todas las relaciones de esta instancia serás borradas también..</p>
    <form action="{{request.get_full_path}}" method="post">
        {% csrf_token %}
        <div class="buttons are-medium columns">
            <div class="column">
                <input type="submit" class="button is-danger is-fullwidth" value="Borrar" />
            </div>
            <div class="column">
                <a href="{{object.get_absolute_url}}" class="button
                         is-warning  is-fullwidth">Volver a detalles</a></div>
        </div>
    </form>
</div>
{% endblock  %}

www_programacion/apps/proyecto/templates/proyecto/valor_curso/create.dj.html
{% extends 'proyecto/base.dj.html' %}
{% load widget_tweaks %}

{% block content_article%}
{% if perms.groups_manager.can_add_emailtemplates %}
<form action="{{request.get_full_path}}" method="post" id="member_form" class="django form">
    {% csrf_token %}

    {% include 'proyecto/valor_curso/fields.dj.html' %}

    <div class="buttons are-medium columns">
        <div class="column">
            <button type="submit" class="button
                          is-primary is-fullwidth">Crear</button></div>
        <div class="column ">
            <a class="button is-warning is-fullwidth" href={% if group %}
               "{% url 'proyecto:coursevalue_detail' object.id %}"
               {% else %}
               "{% url 'proyecto:coursevalue_list' %}"{% endif %}>
                Cancelar</a></div>
    </div>

</form>
{% endif %}
{% endblock content_article %}

www_programacion/apps/proyecto/templates/proyecto/valor_curso/detail.dj.html
{% extends 'proyecto/base.dj.html' %}

{% block content_article%}
<!-- mostrar valor y proyectos-curso que tienen ese valor -->
<div class="columns">
    <div class="column">
        <h4 class="title is-4 has-text-centered">Para {{object.asignacion}}</h4>
        <p>CLP ${{object.precio}}</p>
    </div>    
    <div class="column">
        <h4 class="title is-4 has-text-centered">Proyectos con este valor</h4>        
        <ul>
            {% for project in object.projects.all %}
            <li>
                <a href="{{project.get_absolute_url}}" alt="project.slug_generacion">{{project}}</a>
            </li>
            {% endfor %}
        </ul>


    </div>
</div>
{% endblock content_article %}

www_programacion/apps/proyecto/templates/proyecto/valor_curso/edit.dj.html
{% extends 'proyecto/base.dj.html' %}
{% load widget_tweaks %}

{% block content_article%}
<h2 class="title is-2">Edición de valor para {{object}}</h2>
{% if perms.groups_manager.can_change_emailtemplates %}

<form action="{{request.get_full_path}}" method="post" id="member_form" class="django form">
    {% csrf_token %}

    {% include 'proyecto/valor_curso/fields.dj.html' %}

    <div class="buttons are-medium columns">
        <div class="column">
            <button type="submit" class="button
                          is-primary is-fullwidth">Editar</button></div>
        <div class="column ">
            <a class="button is-warning is-fullwidth" href={% if group %}
               "{% url 'proyecto:coursevalue_detail' object.id %}"
               {% else %}
               "{% url 'proyecto:coursevalue_list' %}"{% endif %}>
                Cancelar</a></div>
    </div>

</form>
{% endif %}
{% endblock content_article %}

www_programacion/apps/proyecto/templates/proyecto/valor_curso/fields.dj.html
{% load static %}
{% load widget_tweaks %}

<!-- first name -->
<div  class="field is-horizontal"  id="field_precio">
    <div class="field-label is-normal">
        <label class="label"
               for="{{form.precio.id_for_label}}">
            {{form.precio.label}}</label> Pesos chilenos
    </div>
    <div class="field-body">
        <div class="control">
            {% render_field form.precio class+="input" %}</div>
        <span class="help is-invalid">{{ form.precio.errors }}</span>
    </div>
</div>

<!-- first name -->
<div  class="field is-horizontal"  id="field_asignacion">
    <div class="field-label is-normal">
        <label class="label"
               for="{{form.asignacion.id_for_label}}">
            {{form.asignacion.label}}</label>
    </div>
    <div class="field-body">
        <div class="control">
            {% render_field form.asignacion class+="input" %}</div>
        <span class="help is-invalid">{{ form.asignacion.errors }}</span>
    </div>
</div>

www_programacion/apps/proyecto/templates/proyecto/valor_curso/list.dj.html
{% extends 'proyecto/base.dj.html' %}

{% block content_proyecto %}
<div class="tile">
<h2 class="title is-2">
    <i class="fa fa-groups-manager-group"></i> Valores
</h2>
</div>
<div class="tile">
<table class="table is-hoverable is-fullwidth is-striped" id="group_list">
    <thead>
        <tr>
            <th>Asignación</th>
            <th>Precio CLP$</th>
            <th>En USD$</th>
            <th class="has-text-right">Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% for value in object_list %}
        <tr>
            <td><a href="{{value.get_absolute_url}}">{{value.asignacion}}</a></td>
            <td>{{value.precio}}</td>
            <td>{{value.usd}}</td>
            <td class="has-text-right">
                <!--PERMISSIONS_HERE-->
                {% if perms.groups_manager.can_change_valor %}
                <a href="{% url 'proyecto:coursevalue_edit' value.id %}"
    class="button is-warning">
                    <i class="fa fa-edit"></i>
                </a>
                {% endif %}
                {% if perms.groups_manager.can_delete_valor %}
                <a href="{% url 'proyecto:coursevalue_delete' value.id %}"
    class="button is-danger">
                    <i class="fa fa-times"></i>
                </a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
{% endblock %}